version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"

  # Maintain dependencies for bun
  - package-ecosystem: "bun"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
